apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-secret
  namespace: telegram
spec:
  refreshInterval: "1h" # How often to refresh the secret
  secretStoreRef:
    name: vault-backend # Reference to the ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: telegram-secret # Name of the Kubernetes secret to create
    creationPolicy: Owner # Controls the lifecycle of the secret (Owner/Orphan/None)
  data:
    - secretKey: TELEGRAM_TOKEN   # Key in the Kubernetes secret
      remoteRef:
        key: telegram_token       # Vault KV path
        property: TOKEN           # Specific property in the Vault secret
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: telegram_token
        property: CHAT_ID
